const $SteamMulti = Java.loadClass('com.gregtechceu.gtceu.common.machine.multiblock.steam.SteamParallelMultiblockMachine');
const LargeMinerMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.electric.LargeMinerMachine");

GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('steam_animal_trapper')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(2, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('steam_ranch')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(3, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('steam_butcher')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 2, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)
    
    event.create('primitive_excavator')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(2, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('vapor_distiller')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 2, 1, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('steam_excavator')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('polymerization_chamber')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 0, 2, 1)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('basic_electric_excavator')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('petrothermal_goo_drilling_rig')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 0, 0, 1)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('launch_pad')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(2, 1, 1, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('data_receiver')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('wind_generator')
        .category('multiblock')
        .setEUIO('out')
        .setMaxIOSize(1, 0, 0, 0) //item input, item output, fluid input, fluid output
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('waterwheel')
        .category('multiblock')
        .setEUIO('out')
        .setMaxIOSize(0, 0, 1, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)

    event.create('decay_generator')
        .category('multiblock')
        .setEUIO('out')
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.BOX_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COOLING)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    
    //Steam Animal Trapper
    event.create('steam_animal_trapper', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('steam_animal_trapper')
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true).recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CCCCC", "FBBBF", "FBBBF", "FFFFF")
        .aisle("CDDDC", "BBBBB", "BBBBB", "FBBBF")
        .aisle("CDDDC", "BBEBB", "BBBBB", "FBBBF")
        .aisle("CDDDC", "BBBBB", "BBBBB", "FBBBF")
        .aisle("CCHCC", "FBBBF", "FBBBF", "FFFFF")
   .where('B', Predicates.any())
   .where('C', Predicates.blocks('gtceu:steam_machine_casing').setMinGlobalLimited(10) // Corrected line
   .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
   .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
   .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
   .where("D", Predicates.blocks("minecraft:dirt"))
   .where("E", Predicates.blocks("minecraft:hay_block"))
   .where("F", Predicates.blocks("gtceu:ceramic_steel_frame"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("gtceu:block/casings/steam/bronze/bottom", "kubejs:block/multiblock/steam_animal_trapper")


    //Steam Ranch
    event.create('steam_ranch', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('steam_ranch')
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true).recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CCCCC", "FIIIF", "FBBBF", "FIIIF", "CAAAC")
        .aisle("CDDDC", "IBBBI", "BBBBB", "IBBBI", "ALLLA")
        .aisle("CDDDC", "IBBBI", "BBBBB", "IBBBI", "ALLLA")
        .aisle("CKGKC", "IIJII", "IBBBI", "IBBBI", "ALLLA")
        .aisle("CDDDC", "IBBBI", "BBBBB", "IBBBI", "ALLLA")
        .aisle("CDDDC", "IBBBI", "BBBBB", "IBBBI", "ALLLA")
        .aisle("CKGKC", "IIJII", "IBBBI", "IBBBI", "ALLLA")
        .aisle("CDDDC", "IBBBI", "BBBBB", "IBBBI", "ALLLA")
        .aisle("CDDDC", "IBBBI", "BBBBB", "IBBBI", "ALLLA")
        .aisle("CCHCC", "FIIIF", "FBBBF", "FIIIF", "CAAAC")
   .where('B', Predicates.any())
   .where('C', Predicates.blocks('gtceu:steam_machine_casing').setMinGlobalLimited(10) // Corrected line
   .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
   .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
   .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
   .where("D", Predicates.blocks("minecraft:dirt"))
   .where("E", Predicates.blocks("minecraft:hay_block"))
   .where("F", Predicates.blocks("gtceu:ceramic_steel_frame"))
   .where("A", Predicates.blocks("gtceu:wood_frame"))
   .where("G", Predicates.blocks("gtceu:bronze_gearbox"))
   .where("I", Predicates.blocks('minecraft:oak_fence'))
   .where("J", Predicates.blocks('minecraft:oak_fence_gate'))
   .where("K", Predicates.blocks('gtceu:steam_machine_casing'))
   .where("L", Predicates.blocks('minecraft:oak_slab'))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("gtceu:block/casings/steam/bronze/bottom", "kubejs:block/multiblock/steam_ranch")

    //Steam Butcher
    event.create('steam_butcher', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('steam_butcher')
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true).recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CCC", "FCF", "FCF", "FCF")
        .aisle("CCC", "CBC", "CBC", "CCC")
        .aisle("CCC", "FHF", "FDF", "FCF")
   .where('B', Predicates.any())
   .where('C', Predicates.blocks('gtceu:steam_machine_casing').setMinGlobalLimited(10) // Corrected line
   .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
   .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
   .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
   .where("D", Predicates.blocks("minecraft:glass"))
   .where("E", Predicates.blocks("minecraft:hay_block"))
   .where("F", Predicates.blocks("gtceu:ceramic_steel_frame"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("gtceu:block/casings/steam/bronze/bottom", "kubejs:block/multiblock/steam_butcher")

    //Primitive Excavator
    event.create('primitive_excavator', 'multiblock')
        //.machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('primitive_excavator')
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true).recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CCC", "CCC", "BDB", "BDB", "BDB", "BBB", "BBB", "BBB")
        .aisle("CCC", "CCC", "DED", "DED", "DED", "BDB", "BDB", "BDB")
        .aisle("CCC", "CHC", "BDB", "BDB", "BDB", "BBB", "BBB", "BBB")
   .where('B', Predicates.any())
   .where('C', Predicates.blocks('kubejs:excavator_bricks').setMinGlobalLimited(10) // Corrected line
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("D", Predicates.blocks("gtceu:wood_frame"))
   .where("E", Predicates.blocks("kubejs:excavator_bricks"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("kubejs:block/excavator_bricks", "kubejs:block/multiblock/primitive_excavator")

    //Vapour distiller
    event.create('vapor_distiller', 'multiblock')
        //.machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('vapor_distiller')
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CCC", "CCC", "DCD", "BBB")
        .aisle("CCC", "CCC", "DED", "BEB")
        .aisle("CCC", "CHC", "DCD", "BBB")
   .where('B', Predicates.any())
   .where('C', Predicates.blocks('gtceu:solid_machine_casing').setMinGlobalLimited(10) // Corrected line
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("D", Predicates.blocks("gtceu:bronze_frame"))
   .where("E", Predicates.blocks("gtceu:steel_pipe_casing"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_casing_solid_steel", "kubejs:block/multiblock/vapor_distiller")

    //Steam Excavator
    event.create('steam_excavator', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('steam_excavator')
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true).recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CCC", "CCC", "BDB", "BDB", "BDB", "BBB", "BBB", "BBB")
        .aisle("CCC", "CCC", "DED", "DED", "DED", "BDB", "BDB", "BDB")
        .aisle("CCC", "CHC", "BDB", "BDB", "BDB", "BBB", "BBB", "BBB")
        .where('B', Predicates.any())
        .where('C', Predicates.blocks('kubejs:bronze_plated_excavator_bricks').setMinGlobalLimited(10) // Corrected line
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
        .where("D", Predicates.blocks("gtceu:ceramic_steel_frame"))
        .where("E", Predicates.blocks("kubejs:bronze_plated_excavator_bricks"))
        .where('H', Predicates.controller(Predicates.blocks(definition.get())))
        .build())
        .workableCasingModel("kubejs:block/bronze_plated_excavator_bricks", "kubejs:block/multiblock/primitive_excavator")

    //Polymerization chamber
    event.create('polymerization_chamber', 'multiblock')
        //.machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('polymerization_chamber')
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("D D D D", "       ", "       ", "       ", "       ", "       ", "       ", "       ",)
        .aisle("       ", " DDDDD ", "  D D  ", "  CCC  ", "  CFC  ", "  CFC  ", "  CCC  ", "       ",)
        .aisle("D     D", " D   D ", " DCCCD ", " CCCCC ", " CE EC ", " CE EC ", " CE EC ", "  CCC  ",)
        .aisle("       ", " D   D ", "  CCC  ", " CCCCC ", " F   F ", " F   F ", " C   C ", "  CFC  ",)
        .aisle("D     D", " D   D ", " DCCCD ", " CCCCC ", " CE EC ", " CE EC ", " CE EC ", "  CCC  ",)
        .aisle("       ", " DDDDD ", "  D D  ", "  CHC  ", "  CCC  ", "  CFC  ", "  CCC  ", "       ",)
        .aisle("D D D D", "       ", "       ", "       ", "       ", "       ", "       ", "       ",)
   .where(' ', Predicates.any())
   .where('C', Predicates.blocks('kubejs:poly_reaction_casing').setMinGlobalLimited(10) // Corrected line
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("D", Predicates.blocks("gtceu:invar_frame"))
   .where("E", Predicates.blocks("gtceu:long_distance_fluid_pipeline"))
   .where("F", Predicates.blocks("gtceu:tempered_glass"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("kubejs:block/poly_reaction_casing", "kubejs:block/multiblock/polymerization_chamber")

    //Steam Compactor
   /*event.create('steam_compactor', 'multiblock')
        .machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('compressor')
        .recipeModifier((machine, recipe) => $SteamMulti.recipeModifier(machine, recipe), true)
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CCC", "DDD", "EEE")
        .aisle("CCC", "DBD", "EEE")
        .aisle("CCC", "DHD", "EEE")
        .where('B', Predicates.any())
        .where('C', Predicates.blocks('minecraft:bricks').setMinGlobalLimited(9) // Corrected line
        .where("D", Predicates.blocks("gtceu:steam_machine_casing"))
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
        .where("E", Predicates.blocks("gtceu:industrial_steam_casing"))
        .where('H', Predicates.controller(Predicates.blocks(definition.get())))
        .build())
        .workableCasingModel("gtceu:block/casings/steam/bronze/bottom", "kubejs:block/multiblock/steam_compactor")*/

    //Basic electric excavator
    event.create('basic_electric_excavator', 'multiblock')
        //.machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('basic_electric_excavator')
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CEC", "CEC", " D ", " D ", " D ", "   ", "   ", "   ")
        .aisle("EEE", "EEE", "DED", "DED", "DED", " D ", " D ", " D ")
        .aisle("CEC", "CHC", " D ", " D ", " D ", "   ", "   ", "   ")
   .where('B', Predicates.any())
   .where('C', Predicates.blocks('gtceu:solid_machine_casing')
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("D", Predicates.blocks("gtceu:galvanized_steel_frame"))
   .where("E", Predicates.blocks("kubejs:conic_casing"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_casing_solid_steel", "kubejs:block/multiblock/basic_electric_excavator")

    //Petrothermal Goo Drilling Rig
    event.create('petrothermal_goo_drilling_rig', 'multiblock')
        //.machine((holder) => new $SteamMulti(holder, 4))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('petrothermal_goo_drilling_rig')
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("D   D", "     ", "     ", "     ", "     ", "     ", "     ", "     ")
        .aisle(" CEC ", " DED ", "  D  ", "  D  ", "  D  ", "     ", "     ", "     ")
        .aisle(" EEE ", " EEE ", " DCD ", " DCD ", " DCD ", "  D  ", "  D  ", "  D  ")
        .aisle(" CEC ", " DHD ", "  D  ", "  D  ", "  D  ", "     ", "     ", "     ")
        .aisle("D   D", "     ", "     ", "     ", "     ", "     ", "     ", "     ")
   .where('B', Predicates.any())
   .where('C', Predicates.blocks('gtceu:ulv_machine_casing')
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("D", Predicates.blocks("gtceu:galvanized_steel_frame"))
   .where("E", Predicates.blocks("gtceu:industrial_steam_casing"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("gtceu:block/casings/voltage/ulv/bottom", "kubejs:block/multiblock/vapor_distiller")

   //Launch Pad
   event.create('launch_pad', 'multiblock')
       //.machine((holder) => new $SteamMulti(holder, 4))
       .rotationState(RotationState.NON_Y_AXIS)
       .recipeType('launch_pad')
       .pattern(definition => FactoryBlockPattern.start()
       .aisle("CCCCC", "SD DS", "S D S", "SD DS", "S D S", "SD DS", "S D S", "SD DS")
       .aisle("CCCCC", "D   D", "     ", "D   D", "     ", "D   D", "     ", "D   D")
       .aisle("CCCCC", "     ", "D   D", "     ", "D   D", "     ", "D   D", "     ")
       .aisle("CCCCC", "D   D", "     ", "D   D", "     ", "D   D", "     ", "D   D")
       .aisle("CCCCC", "S   S", "S   S", "S   S", "SSHSS", "SD DS", "S D S", "SD DS")
   .where('B', Predicates.any())
   .where('S', Predicates.blocks('kubejs:spaceflight_casing')
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("D", Predicates.blocks("gtceu:galvanized_steel_frame"))
   .where("C", Predicates.blocks("kubejs:conic_casing"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("kubejs:block/spaceflight_casing", "kubejs:block/multiblock/launch_pad")

    //Data Receiver
   event.create('data_receiver', 'multiblock')
       //.machine((holder) => new $SteamMulti(holder, 4))
       .rotationState(RotationState.NON_Y_AXIS)
       .recipeType('data_receiver')
       .pattern(definition => FactoryBlockPattern.start()
       .aisle("D    D", "      ", "      ", "      ", "   C  ", "    C ", "      ", "      ", "      ")
       .aisle("      ", " D   D", "     D", "  CC  ", "    C ", "     C", "     C", " F    ", "      ")
       .aisle("      ", "      ", "  D   ", " CCC D", "    CD", "     C", "  E  C", "     C", "    C ")
       .aisle("      ", "      ", "      ", " CCCD ", "C  CC ", "   ECC", "    CC", "    CC", "    C ")
       .aisle("    SS", "    SS", "    DD", "   DDD", " CCCD ", "C  CC ", "   CC ", "   CC ", "  CC  ")
       .aisle("D   SS", " D  HS", " D  DD", "  D D ", "  D   ", " CCC  ", " CCC  ", "  CC  ", "      ")
   .where('B', Predicates.any())
   .where('S', Predicates.blocks('kubejs:spaceflight_casing')
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("D", Predicates.blocks("gtceu:spacefaring_steel_frame"))
   .where("C", Predicates.blocks("gtceu:clean_machine_casing"))
   .where("E", Predicates.blocks("gtceu:chromium_block"))
   .where("F", Predicates.blocks("minecraft:emerald_block"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
    .workableCasingModel("kubejs:block/spaceflight_casing", "kubejs:block/multiblock/data_receiver")

   

   //Wind Generator
   event.create('wind_generator', 'multiblock')
       //.machine((holder) => new $SteamMulti(holder, 4))
       .rotationState(RotationState.NON_Y_AXIS)
       .recipeType('wind_generator')
       .pattern(definition => FactoryBlockPattern.start()
       .aisle("  SSS  ", "   S   ", "   S   ", "   S   ", "   S   ", "       ", "       ", "       ")
       .aisle("  SSS  ", "  SES  ", "  SAS  ", "  SAS  ", "  SGS  ", "   S   ", "       ", "       ")
       .aisle("  SSS  ", "W  H  W", " W S W ", "  WSW  ", "   G   ", "  W W  ", " W   W ", "W     W")
   .where('B', Predicates.any())
   .where('S', Predicates.blocks('kubejs:conic_casing')
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("E", Predicates.blocks("kubejs:electromagnet_casing"))
   .where("A", Predicates.blocks("create:shaft"))
   .where("G", Predicates.blocks("gtceu:steel_gearbox"))
   .where("W", Predicates.blocks("minecraft:white_wool"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
   .workableCasingModel("kubejs:block/conic_casing", "kubejs:block/multiblock/energy_producer")

   //Waterwheel
   event.create('waterwheel', 'multiblock')
       //.machine((holder) => new $SteamMulti(holder, 4))
       .rotationState(RotationState.NON_Y_AXIS)
       .recipeType('waterwheel')
       .pattern(definition => FactoryBlockPattern.start()
       .aisle("SSSSS", "SSSSS", " SSS ")
       .aisle("SSSSS", "ECCCE", " WWW ")
       .aisle("SSSSS", "S   S", "     ")
       .aisle("SSSSS", "SSHSS", "     ")
   .where('B', Predicates.any())
   .where('S', Predicates.blocks('kubejs:conic_casing')
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("E", Predicates.blocks("kubejs:electromagnet_casing"))
   .where("C", Predicates.blocks("create:water_wheel"))
   .where("W", Predicates.blocks("minecraft:water"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
   .workableCasingModel("kubejs:block/conic_casing", "kubejs:block/multiblock/energy_producer")

   //Decay generator
   event.create('decay_generator', 'multiblock')
       //.machine((holder) => new $SteamMulti(holder, 4))
       .rotationState(RotationState.NON_Y_AXIS)
       .recipeType('decay_generator')
       .pattern(definition => FactoryBlockPattern.start()
       .aisle("SSSSS", "SGGGS", "SGGGS", "SGGGS", "SSSSS")
       .aisle("SGGGS", "GR RG", "G A G", "GR RG", "SGGGS")
       .aisle("SGGGS", "G A G", "GAUAG", "G A G", "SGGGS")
       .aisle("SGGGS", "GR RG", "G A G", "GR RG", "SGGGS")
       .aisle("SSHSS", "SGGGS", "SGGGS", "SGGGS", "SSSSS")
   .where('B', Predicates.any())
   .where('S', Predicates.blocks('kubejs:conic_casing')
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("R", Predicates.blocks("kubejs:radiation_collector"))
   .where("A", Predicates.blocks("create:shaft"))
   .where("U", Predicates.blocks("gtceu:uranium_235_block"))
   .where("G", Predicates.blocks("gtceu:tempered_glass"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
   .build())
   .workableCasingModel("kubejs:block/conic_casing", "kubejs:block/multiblock/energy_producer")
   }); 