// priority: 0
ServerEvents.recipes(event => {
    event.recipes.gtceu.mixer("kubejs:organics_fluid_from_glauconite")
        .itemInputs("4x gtceu:glauconite_sand_dust")
        .inputFluids(Fluid.of("gtceu:salt_water", 1000))
        .outputFluids(Fluid.of("gtceu:organics_extraction_fluid", 2000))
        .duration(400)
        .EUt(3)

    event.recipes.gtceu.mixer("kubejs:organics_fluid_from_soapstone")
        .itemInputs("4x gtceu:soapstone_dust")
        .inputFluids(Fluid.of("gtceu:salt_water", 1000))
        .outputFluids(Fluid.of("gtceu:organics_extraction_fluid", 2000))
        .duration(400)
        .EUt(3)

    event.recipes.gtceu.bio_reactor("kubejs:bio_chaff_separate")
        .itemInputs("8x gtceu:bio_chaff")
        .inputFluids(Fluid.of("gtceu:organics_extraction_fluid", 250))
        .itemOutputs("1x kubejs:rubisco_enzyme")
        .outputFluids(Fluid.of("gtceu:adp", 100))
        .outputFluids(Fluid.of("gtceu:nadp_mais", 100))
        .outputFluids(Fluid.of("gtceu:rubp", 100))
        .duration(400)
        .EUt(3)

    event.recipes.gtceu.bio_reactor("kubejs:3_pga_make")
        .inputFluids(Fluid.of("gtceu:rubp", 1000))
        .inputFluids(Fluid.of("gtceu:carbon_dioxide", 1000))
        .notConsumable("1x kubejs:rubisco_enzyme")
        .outputFluids(Fluid.of("gtceu:3_pga", 2000))
        .duration(400)
        .EUt(3)

    event.recipes.gtceu.bio_reactor("kubejs:1_3_bpg_make")
        .inputFluids(Fluid.of("gtceu:3_pga", 1000))
        .inputFluids(Fluid.of("gtceu:atp", 1000))
        .outputFluids(Fluid.of("gtceu:1_3_bpg", 1000))
        .outputFluids(Fluid.of("gtceu:adp", 1000))
        .duration(400)
        .EUt(3)

     event.recipes.gtceu.bio_reactor("kubejs:pgal_make")
        .inputFluids(Fluid.of("gtceu:1_3_bpg", 1000))
        .inputFluids(Fluid.of("gtceu:nadph", 1000))
        .outputFluids(Fluid.of("gtceu:pgal", 1000))
        .outputFluids(Fluid.of("gtceu:nadp_mais", 1000))
        .outputFluids(Fluid.of("gtceu:h_plus", 1000))
        .itemOutputs("1x gtceu:phosphate_dust")
        .duration(400)
        .EUt(3)

    event.recipes.gtceu.bio_reactor("kubejs:glucose_make")
        .inputFluids(Fluid.of("gtceu:pgal", 6000))
        .itemOutputs("3x gtceu:glucose_dust")
        .itemOutputs("2x gtceu:phosphate_dust")
        .duration(400)
        .EUt(3)

    event.recipes.gtceu.bio_reactor("kubejs:rubp_regen")
        .inputFluids(Fluid.of("gtceu:pgal", 3000))
        .inputFluids(Fluid.of("gtceu:atp", 3000))
        .outputFluids(Fluid.of("gtceu:rubp", 1800))
        .itemOutputs("2x gtceu:phosphate_dust")
        .duration(400)
        .EUt(3)

    event.recipes.gtceu.bio_reactor("kubejs:atp_regen")
        .inputFluids(Fluid.of("gtceu:adp", 1000))
        .itemInputs("1x gtceu:phosphate_dust")
        .outputFluids(Fluid.of("gtceu:atp", 1000))
        .duration(400)
        .EUt(3)

    event.recipes.gtceu.bio_reactor("kubejs:nadph_regen")
        .inputFluids(Fluid.of("gtceu:nadp_mais", 1000))
        .inputFluids(Fluid.of("gtceu:h_plus", 1000))
        .outputFluids(Fluid.of("gtceu:nadph", 1000))
        .duration(400)
        .EUt(3)
})