StartupEvents.registry('block', event => {
  event.create('ghillie')
    .displayName('Ghillie')
    .soundType('stone')
    .hardness(1.5)
    .resistance(6.0)
    .texture("top", "ghillie_top")
    .texture("bottom", "ghillie_top")
    .texture("left", "ghillie")
    .texture("right", "ghillie")
    .texture("front", "ghillie")
    .texture("back", "ghillie")

  event.create('glacio')
    .displayName('Glacio')
    .soundType('stone')
    .hardness(1.5)
    .resistance(6.0)

   event.create('vicinus')
    .displayName('Vicinus')
    .soundType('stone')
    .hardness(1.5)
    .resistance(6.0)

   event.create('proxima_b')
    .displayName('Proxima b')
    .soundType('stone')
    .hardness(1.5)
    .resistance(6.0)

   event.create('proxima_d')
    .displayName('Proxima d')
    .soundType('stone')
    .hardness(1.5)
    .resistance(6.0)

   event.create('red_dwarf')
    .displayName('Proxima Centauri')
    .soundType('stone')
    .hardness(1.5)
    .resistance(6.0)

   event.create('orange_dwarf')
    .displayName('Phenera')
    .soundType('stone')
    .hardness(1.5)
    .resistance(6.0)

   event.create('neutron_star')
    .displayName('Sabine-16')
    .soundType('stone')
    .hardness(1.5)
    .resistance(6.0)
})